//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FavDeals.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Deal
    {
        public int DId { get; set; }
        public string DSource { get; set; }
        public string DProduct { get; set; }
        public string DLink { get; set; }
        public decimal DOrgPrice { get; set; }
        public decimal DOffPrice { get; set; }
    }
}
